#!/bin/sh

PID=$( xdo pid | xargs -r ps -o comm= -q )

[ "$PID" = "xterm" ] && PLAYER="devour mpv" || PLAYER="mpv"

CACHE="/tmp/search-yt"

link_get(){
  LINK="https://youtube.com$( awk -F '"' -v SELECTION="$ID" \
    ' NR == SELECTION { print $2 } ' "${CACHE}" )"
}

results_show(){
  s -n 20 ${QUERY} |
  sed '0~2d;s|\x1B\[[0-9;]*[a-zA-Z]||g' |
  dmenu -l 8 |
  awk -F '[\\[\\]]' '{print $2}'
}

[ -n "$1" ] && QUERY=$@ || QUERY=$(echo '' | dmenu -p "Search youtube: ")

[ -n "$QUERY" ] && ID=$(results_show) || exit

[ -n "$ID" ] && link_get && ${PLAYER} "${LINK}"
