#!/bin/sh

NC="\033[0m"
RED="\033[1;31m"
YELLOW="\033[0;33m"

CACHE="/tmp/search-yt"
INSTANCE="https://invidious.snopyta.org/search?q="


curl -s "$INSTANCE$1" |
  grep -o -e 'href\=\"/watch.**</a>' -e '.* views' \
    -e 'href\=\"/channel.**</a>' -e 'length.*</p' \
    -e '>Shared.*</div' |
  head -n 5 |
  awk -F '[<>]' '{print $2} /views/ {print} /watch/ {print $1}'


# i'll try to use this format
# printf -- "\033[1;31m\nCommand Line App For Downloading YouTube Videos\n" && printf "\033[0;33m[1]-> DistroTub | 14:59 | 21K views | 1 year ago\n\n"
